# Generated by Django 4.1.5 on 2023-01-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('target_url', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('clicks', models.IntegerField()),
            ],
        ),
    ]
